### ISSUE TITLE
How to create the service account file from secret key?

### ISSUE THREAD

**Issue by steinko** [zxyle/publish-gae-action#2]
I want to use this template to depoy my Docker container to Google Cloud App Engine.
https://github.com/steinko/lumdb/blob/master/.github/workflows/google.yml
I have place the service account key an email as secret keys 
https://github.com/steinko/lumdb/settings/secrets
A errr occure when  GIthub execute the Github Action
ERROR: (gcloud.auth.activate-service-account) Unable to read file [client-secret.json]: [Errno 2] No such file or directory: 'client-secret.json'
##[error]Process completed with exit code 1.

 https://github.com/steinko/lumdb/runs/428578324

What must I do to get the data from the service accout key  to the client-secret.json?

**Comment by zxyle** [comment]
You can refer to this [article](https://cloud.google.com/solutions/continuous-delivery-with-travis-ci#creating_credentials). It will teach you how to create the keys needed for deployment. After this, Use this  `cat my-key.json | base64` command to convert to base64, Then put it to https://github.com/steinko/lumdb/settings/secrets.
